package com.assetneuron.whatsapp.dto;

public enum ResponseCodes {

    // Success messages
    WORK_ITEMS_RETRIEVAL_SUCCESSFUL,
    WORK_ORDER_DETAIL_RETRIEVAL_SUCCESSFUL,
    TASKS_RETRIEVAL_SUCCESSFUL,
    HOURS_LOGGED_SUCCESSFUL,
    ASSET_RATING_SAVED_SUCCESSFUL,
    COMMENT_ADDED_SUCCESSFUL,
    USER_RETRIEVAL_SUCCESSFUL,
    SUPERVISOR_RETRIEVAL_SUCCESSFUL,

    // Error messages
    ERR_FAILED_TO_RETRIEVE_WORK_ITEMS,
    ERR_INVALID_ITEM_TYPE,
    ERR_FAILED_TO_RETRIEVE_WORK_ORDER_DETAIL,
    ERR_FAILED_TO_RETRIEVE_TASKS,
    ERR_FAILED_TO_LOG_HOURS,
    ERR_FAILED_TO_SAVE_ASSET_RATING,
    ERR_FAILED_TO_ADD_COMMENT,
    ERR_FAILED_TO_RETRIEVE_USER,
    ERR_FAILED_TO_RETRIEVE_SUPERVISOR,
    BAD_REQUEST,
    UNAUTHORIZED,
    INTERNAL_SERVER_ERROR
}

